Feature/nevisaccessapp 5317 extend eslint configuration
nevissecurity/nevis-mobile-authentication-sdk-example-app-react pull request #6
Opened 2023-11-08 09:49 UTC by daniel-toth-leeder

2023-11-08 10:15 UTC, tamas-toth approved these changes

2023-11-14 13:30 UTC, balazs-gerlei requested changes

2023-11-14 13:30 UTC, balazs-gerlei commented on src/screens/HomeScreen.tsx
> +	}, []);
I think the dependencies here were fine, they are memoized methods in the same component. So I think you don't need to remove them!

2023-11-14 14:56 UTC, balazs-gerlei approved these changes

2023-11-14 14:56 UTC, merged